const mongoose = require('mongoose');

const vehicleSchema = new mongoose.Schema({
  vehicleNo: String,
  chassisNo: String,
  mobileNo: String,
  vehiclePermitType: String,
  seatingCapacityExcludingDriver: String,
  sleeperCapacityExcludingDriver: String,
  borderBarrier: String,
  totalAmount: String,
  ownerName: String,
  fromState: String,
  uptNumber:String,
  bankReferenceNumber:String,
  state:String,
  vehicleClass: String,
  serviceType: String,
  taxMode: String,
  taxFromDate: String,
  taxUptoDate: String,
  paymentMode: String,
  checkpostName: String,
  permitType: String,
  grossVehicleWeight: String,
  unladenWeight: String,
  fitnessValidity: String,
  insuranceValidity: String,
  taxValidity: String,
  floorArea: String,
  infraCess: String,
  mvTax: String,
  cess: String,
  permitFee: String,
  permitAuthorizationNo: String,
  permitEndoresment: String,
  routeOfTheJourney: String,
  purposeOfJourney: String,
  sgst: String,
  cgst: String,
  registrationType: String,
  puccValidity: String,
  permitAuthorizationValidity: String,
  permitNo: String,
  permit: String,
  pushbackSeats: String,
  tipperBody: String,
  saleAmount: String,
  ordinarySeats: String,
  issuingAuthority: String,
  goodsName: String,
  fuelType: String,
  vehicleCategory: String,
  greenTaxValidity: String,
  cessPaidDate: String,
  regnDate: String,
  cubicCap: String,
  permitCategory: String,
  driverName: String,
  dlNumber: String,
  dlValidUptoDate: String,
  counterSignatureFree: String,
  numberOfPeriod: String,
  basicPermitValidity: String,
  permitNumber: String,
  taxAmount: String,
  barrierName: String,
  districtName: String,
  additionalSeatingCapacity: String,
  additionalSleeperCapacity: String,
  applicationFee: String,
  permitUpto: String,
  permitFrom: String,
  adminName:String
});

module.exports = mongoose.model('Vehicle', vehicleSchema);
